import type { SeoAuditResult, SeoAuditCategory, MiniKeywordResult } from '@jackpotkeywords/shared';
import { SEO_AUDIT_CATEGORY_LABELS } from '@jackpotkeywords/shared';

const BRAND_COLOR: [number, number, number] = [234, 179, 8]; // jackpot-500 amber
const DARK_COLOR: [number, number, number] = [17, 24, 39]; // gray-900
const LIGHT_GRAY: [number, number, number] = [107, 114, 128];

const STATUS_COLORS = {
  pass: [34, 197, 94] as [number, number, number],
  warning: [234, 179, 8] as [number, number, number],
  fail: [239, 68, 68] as [number, number, number],
  info: [107, 114, 128] as [number, number, number],
};

const IMPACT_COLORS = {
  high: [239, 68, 68] as [number, number, number],
  medium: [234, 179, 8] as [number, number, number],
  low: [107, 114, 128] as [number, number, number],
};

const CATEGORIES: SeoAuditCategory[] = [
  'technical', 'content', 'crawlability', 'structured_data', 'local_geo', 'social_sharing',
];

type AutoTableDoc = any;

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return iso;
  }
}

function scoreColor(score: number): [number, number, number] {
  if (score >= 80) return [34, 197, 94];
  if (score >= 60) return [234, 179, 8];
  return [239, 68, 68];
}

function impactEffortRank(r: { impact: string; effort: string }): number {
  const impactWeight: Record<string, number> = { high: 3, medium: 2, low: 1 };
  const effortWeight: Record<string, number> = { quick: 3, moderate: 2, significant: 1 };
  return (impactWeight[r.impact] || 0) * 10 + (effortWeight[r.effort] || 0);
}

function drawFooter(doc: AutoTableDoc, pageNum: number, totalPages: number) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(...LIGHT_GRAY);
  doc.text('Generated by JackpotKeywords — https://jackpotkeywords.web.app', 14, pageH - 8);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 14, pageH - 8, { align: 'right' });
}

function finalY(doc: AutoTableDoc): number {
  return doc.lastAutoTable?.finalY ?? 20;
}

export async function exportAuditPdf(
  result: SeoAuditResult,
  keywordPreview: MiniKeywordResult[] | null | undefined,
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const autoTableModule = await import('jspdf-autotable');
  const autoTable = (autoTableModule as any).default || autoTableModule;

  const doc = new jsPDF({ unit: 'mm', format: 'a4' }) as AutoTableDoc;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const domain = result.domain.replace(/^https?:\/\//, '');

  // ----- Section 1: Cover -----
  doc.setFillColor(...DARK_COLOR);
  doc.rect(0, 0, pageW, pageH, 'F');

  doc.setTextColor(...BRAND_COLOR);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('JackpotKeywords', pageW / 2, 40, { align: 'center' });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.text('SEO Audit Report', pageW / 2, 52, { align: 'center' });

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(domain, pageW / 2, 90, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  doc.text(formatDate(result.createdAt), pageW / 2, 100, { align: 'center' });

  // Score badge
  const badgeY = 130;
  const scoreCol = scoreColor(result.overallScore);
  doc.setFillColor(...scoreCol);
  doc.circle(pageW / 2, badgeY, 24, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text(String(result.overallScore), pageW / 2, badgeY + 4, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...LIGHT_GRAY);
  doc.text('Overall Score', pageW / 2, badgeY + 36, { align: 'center' });

  // ----- Section 2: Executive Summary -----
  doc.addPage();
  doc.setTextColor(...DARK_COLOR);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);

  const totalChecks = result.checks.length;
  const passed = result.checks.filter((c) => c.status === 'pass').length;
  const warnings = result.checks.filter((c) => c.status === 'warning').length;
  const failed = result.checks.filter((c) => c.status === 'fail').length;
  const highPriorityIssues = result.checks.filter((c) => c.status !== 'pass' && c.priority === 'high').length;

  const summaryLines = [
    `We analyzed ${result.metadata.pagesAnalyzed} page${result.metadata.pagesAnalyzed === 1 ? '' : 's'} on ${domain} across ${totalChecks} SEO checks.`,
    `${passed} checks passed, ${warnings} have warnings, and ${failed} failed outright.`,
    highPriorityIssues > 0
      ? `${highPriorityIssues} high-priority issue${highPriorityIssues === 1 ? '' : 's'} require attention.`
      : 'No high-priority issues were detected.',
  ];
  let y = 32;
  for (const line of summaryLines) {
    const lines = doc.splitTextToSize(line, pageW - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 2;
  }

  // Category scorecard table
  autoTable(doc, {
    startY: y + 4,
    head: [['Category', 'Score', 'Passed', 'Total']],
    body: CATEGORIES.map((cat) => {
      const cs = result.categoryScores[cat];
      return [
        SEO_AUDIT_CATEGORY_LABELS[cat],
        `${cs.score}/100`,
        String(cs.passed),
        String(cs.total),
      ];
    }),
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: DARK_COLOR, textColor: 255, fontStyle: 'bold' },
    didParseCell: (data: any) => {
      if (data.section === 'body' && data.column.index === 1) {
        const scoreStr = String(data.cell.raw || '');
        const match = scoreStr.match(/^(\d+)/);
        if (match) {
          const score = parseInt(match[1], 10);
          data.cell.styles.textColor = scoreColor(score);
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
  });

  // ----- Section 3: Priority Recommendations -----
  const priorityRecs = [...result.recommendations]
    .filter((r) => !r.title.startsWith('\u2022\u2022\u2022'))
    .sort((a, b) => impactEffortRank(b) - impactEffortRank(a))
    .slice(0, 5);

  if (priorityRecs.length > 0) {
    doc.addPage();
    doc.setTextColor(...DARK_COLOR);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Priority Recommendations', 14, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text('Top actions ranked by impact and effort — tackle these first.', 14, 30);

    autoTable(doc, {
      startY: 36,
      head: [['#', 'Recommendation', 'Impact', 'Effort', 'Category']],
      body: priorityRecs.map((r, i) => [
        String(i + 1),
        { content: `${r.title}\n${r.description}`, styles: { fontStyle: 'normal' } },
        r.impact.toUpperCase(),
        r.effort.toUpperCase(),
        SEO_AUDIT_CATEGORY_LABELS[r.category as SeoAuditCategory] || r.category,
      ]),
      styles: { fontSize: 9, cellPadding: 3, valign: 'top' },
      headStyles: { fillColor: DARK_COLOR, textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 20, halign: 'center' },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 35 },
      },
      didParseCell: (data: any) => {
        if (data.section === 'body' && data.column.index === 2) {
          const imp = String(data.cell.raw || '').toLowerCase();
          const col = IMPACT_COLORS[imp as keyof typeof IMPACT_COLORS];
          if (col) {
            data.cell.styles.textColor = col;
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
    });
  }

  // ----- Section 4: Detailed Checklist by Category -----
  doc.addPage();
  doc.setTextColor(...DARK_COLOR);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Checklist', 14, 22);

  let curY = 30;
  for (const cat of CATEGORIES) {
    const checks = result.checks.filter((c) => c.category === cat);
    if (checks.length === 0) continue;

    if (curY > pageH - 60) {
      doc.addPage();
      curY = 22;
    }

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_COLOR);
    doc.text(SEO_AUDIT_CATEGORY_LABELS[cat], 14, curY);
    curY += 4;

    autoTable(doc, {
      startY: curY,
      head: [['Status', 'Check', 'Priority', 'Details']],
      body: checks.map((c) => [
        c.status.toUpperCase(),
        c.label,
        c.priority.toUpperCase(),
        c.recommendation || c.details,
      ]),
      styles: { fontSize: 8, cellPadding: 2, valign: 'top', overflow: 'linebreak' },
      headStyles: { fillColor: DARK_COLOR, textColor: 255, fontStyle: 'bold', fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 18, halign: 'center' },
        1: { cellWidth: 55 },
        2: { cellWidth: 18, halign: 'center' },
        3: { cellWidth: 'auto' },
      },
      didParseCell: (data: any) => {
        if (data.section === 'body' && data.column.index === 0) {
          const st = String(data.cell.raw || '').toLowerCase();
          const col = STATUS_COLORS[st as keyof typeof STATUS_COLORS];
          if (col) {
            data.cell.styles.textColor = col;
            data.cell.styles.fontStyle = 'bold';
          }
        }
      },
    });
    curY = finalY(doc) + 6;
  }

  // ----- Section 5: Keyword Opportunities -----
  const realKeywords = (keywordPreview || []).filter(
    (k) => !k.keyword.startsWith('\u2022\u2022\u2022') && k.monthlyVolume >= 10,
  );
  if (realKeywords.length > 0) {
    doc.addPage();
    doc.setTextColor(...DARK_COLOR);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Keyword Opportunities', 14, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(`Real search volume and CPC from Google Ads for ${domain}.`, 14, 30);

    autoTable(doc, {
      startY: 36,
      head: [['Keyword', 'Volume/mo', 'CPC Range', 'Competition']],
      body: realKeywords.slice(0, 100).map((k) => [
        k.keyword,
        k.monthlyVolume.toLocaleString(),
        `$${k.lowCpc.toFixed(2)}–$${k.highCpc.toFixed(2)}`,
        k.competition,
      ]),
      styles: { fontSize: 9, cellPadding: 2.5 },
      headStyles: { fillColor: DARK_COLOR, textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'center' },
      },
    });
  }

  // ----- Section 6: Page-by-page Findings -----
  if (result.pageResults && result.pageResults.length > 0) {
    doc.addPage();
    doc.setTextColor(...DARK_COLOR);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Page-by-Page Findings', 14, 22);

    let pageY = 32;
    for (const p of result.pageResults) {
      if (pageY > pageH - 50) {
        doc.addPage();
        pageY = 22;
      }
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...DARK_COLOR);
      const urlLines = doc.splitTextToSize(p.url, pageW - 28);
      doc.text(urlLines, 14, pageY);
      pageY += urlLines.length * 5;

      const details: string[][] = [];
      if (p.title) details.push(['Title', p.title]);
      if (p.metaDescription) details.push(['Meta description', p.metaDescription]);
      if (p.h1) details.push(['H1', p.h1]);
      if (typeof p.wordCount === 'number') details.push(['Word count', String(p.wordCount)]);

      if (details.length > 0) {
        autoTable(doc, {
          startY: pageY + 1,
          body: details,
          styles: { fontSize: 9, cellPadding: 2 },
          columnStyles: {
            0: { cellWidth: 35, fontStyle: 'bold' },
            1: { cellWidth: 'auto' },
          },
          theme: 'plain',
        });
        pageY = finalY(doc) + 4;
      }

      if (p.issues && p.issues.length > 0) {
        autoTable(doc, {
          startY: pageY,
          head: [['Status', 'Issue']],
          body: p.issues.map((i) => [i.status.toUpperCase(), i.label]),
          styles: { fontSize: 8, cellPadding: 2 },
          headStyles: { fillColor: [230, 230, 230], textColor: DARK_COLOR, fontStyle: 'bold', fontSize: 8 },
          columnStyles: { 0: { cellWidth: 18, halign: 'center' } },
          didParseCell: (data: any) => {
            if (data.section === 'body' && data.column.index === 0) {
              const st = String(data.cell.raw || '').toLowerCase();
              const col = STATUS_COLORS[st as keyof typeof STATUS_COLORS];
              if (col) {
                data.cell.styles.textColor = col;
                data.cell.styles.fontStyle = 'bold';
              }
            }
          },
        });
        pageY = finalY(doc) + 6;
      } else {
        pageY += 4;
      }
    }
  }

  // ----- Section 7: Action Plan -----
  const quickWins = [...result.recommendations]
    .filter((r) => !r.title.startsWith('\u2022\u2022\u2022'))
    .sort((a, b) => impactEffortRank(b) - impactEffortRank(a))
    .slice(0, 3);

  if (quickWins.length > 0) {
    doc.addPage();
    doc.setTextColor(...DARK_COLOR);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Action Plan — Next 3 Steps', 14, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text('Tackle these high-impact, quick-effort items first for the biggest gains.', 14, 30);

    let stepY = 40;
    for (let i = 0; i < quickWins.length; i++) {
      const r = quickWins[i];
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND_COLOR);
      doc.text(`${i + 1}.`, 14, stepY);

      doc.setTextColor(...DARK_COLOR);
      doc.setFontSize(12);
      doc.text(r.title, 22, stepY);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      const descLines = doc.splitTextToSize(r.description, pageW - 40);
      doc.text(descLines, 22, stepY + 6);
      stepY += 6 + descLines.length * 5 + 10;

      if (stepY > pageH - 40 && i < quickWins.length - 1) {
        doc.addPage();
        stepY = 22;
      }
    }
  }

  // ----- Footers on every page -----
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i === 1) continue; // cover page stays clean
    drawFooter(doc, i, totalPages);
  }

  const filename = `jackpotkeywords-audit-${domain.replace(/[^a-z0-9.-]/gi, '-')}.pdf`;
  doc.save(filename);
}
